copy CI scripts from Hunter

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,55 +2,88 @@ language: cpp
 
 sudo: false
     
-matrix:
-  include:
-    - os: linux
-      addons: {apt: {packages: [g++-6] , sources: [ubuntu-toolchain-r-test]}}
-      env:
-        - BUILD_TYPE=Release
-        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
-    - os: linux
-      addons: {apt: {packages: [clang-3.9,llvm-3.9-dev,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test,llvm-toolchain-precise-3.9]}}
-      env: 
-        - BUILD_TYPE=Release 
-        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
-    - os: osx    
-      osx_image: xcode8.3
-      env: 
-        - BUILD_TYPE=Release
-        - MATRIX_EVAL="CC=clang && CXX=clang++"
-    - os: osx
-      osx_image: xcode8.3
-      env: 
-        - BUILD_TYPE=Release
-        - MATRIX_EVAL="brew cask uninstall oclint && brew install gcc6 && CC=gcc-6 && CXX=g++-6"
-    
 cache:
   directories:
     - $HOME/.local
     - $HOME/.hunter
-        
-before_install:
-  - eval "${MATRIX_EVAL}"
-  
-install:
-  - |
-    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-      mkdir -p $HOME/.local
-      CMAKE_URL="http://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
-      if [ ! -e $HOME/.local/bin/cmake ]; then
-        echo "CMake not found in the cache, get and extract it..."
-        travis_retry curl -L ${CMAKE_URL} \
-            | tar -xz -C $HOME/.local --strip-components=1
-      else
-        echo "Using cached CMake"
-      fi
-    fi
-  - |
-    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
-      brew upgrade cmake || brew install cmake
-    fi
     
+matrix:
+  include:
+    # Linux {
+
+    - os: linux
+      env: >
+        TOOLCHAIN=clang-cxx17
+        
+    - os: linux
+      env: >
+        TOOLCHAIN=gcc-7-cxx17
+        
+    - os: linux
+      env: >
+        TOOLCHAIN=analyze-cxx17
+        
+    - os: linux
+      env: >
+        TOOLCHAIN=sanitize-address-cxx17
+        
+    - os: linux
+      env: >
+        TOOLCHAIN=sanitize-leak-cxx17
+        
+    - os: linux
+      env: >
+        TOOLCHAIN=sanitize-thread-cxx17
+        
+    # }
+
+    # OSX {
+
+    - os: osx
+      osx_image: xcode9.4
+      env: >
+        TOOLCHAIN=osx-10-13-make-cxx14
+        
+    - os: osx
+      osx_image: xcode9.4
+      env: >
+        TOOLCHAIN=osx-10-13-cxx14
+        
+    # }
+
+install:
+  # Info about OS
+  - uname -a
+
+  # Info about available disk space
+  - df -h $HOME
+
+  # Disable autoupdate
+  # * https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
+  - export HOMEBREW_NO_AUTO_UPDATE=1
+
+  # Install Python 3
+  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew upgrade python || echo "Ignoring failure..."; fi
+  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi
+
+  # Install Python package 'requests'
+  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
+  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
+  - if [[ "`uname`" == "Darwin" ]]; then pip3 install gitpython; fi
+  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi
+  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user gitpython; fi
+
+  # Install latest Polly toolchains and scripts
+  - wget https://github.com/ruslo/polly/archive/master.zip
+  - unzip master.zip
+  - POLLY_ROOT="`pwd`/polly-master"
+  - export PATH="${POLLY_ROOT}/bin:${PATH}"
+
+  # Install dependencies (CMake, Android NDK)
+  - install-ci-dependencies.py --prune-archives
+
+  # Tune locations
+  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"
+
 script:
-  - cmake . -B_build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPOST_BUILD_TESTS=OFF -DHUNTER_JOBS_NUMBER=8 -DCMAKE_VERBOSE_MAKEFILE=ON
-  - cmake --build _build && cmake --build _build --target test
+  - "build.py --toolchain ${TOOLCHAIN} --config Release --verbose --fwd POST_BUILD_TESTS=FALSE --test"
